#!/usr/bin/env python3
"""
Generate tokens.css from the Figma variables in research/raw/home.json.

Same approach as firefighterpfister: Figma pins three discrete breakpoint
stops (Mobile 375 / Tablet ~768-820 / Desktop 1440); every responsive token
is emitted as a two-segment clamp() so it hits all three stops exactly and
stays smooth in between, rather than a single ramp that would undershoot
tokens whose tablet and desktop values happen to be equal.

Values below are read directly off the Color Tokens / Color Primitives /
Fonts / Layout Spacing variable collections in the scene graph (see
research/raw/home.json -> nodeById -> type VARIABLE). Semantic color
aliases were resolved by matching each alias's VariableID target against
the primitives that share it -- e.g. Text/H1 and Page Elements/Background
Inverse both point at the same VariableID (493:5, Kingfisher), so an H1's
default ink is literally the same navy as an "inverse" section's
background.

Run:  python3 design/tokens/generate_tokens.py
"""

from pathlib import Path

VW_MIN, VW_TABLET, VW_MAX = 375, 768, 1440
ROOT_FONT = 16

# Colors/* variables, Color Primitives collection, Mode 1.
PRIMITIVES = [
    ("black", "#000000"),
    ("white", "#FFFFFF"),
    ("desert-cream", "#FFF8EC"),
    ("kingfisher", "#1F3A5F"),
    ("salmon", "#DF6951"),
    ("shallow-lagoon", "#7DC9BE"),
    ("zesty-lemon", "#EFBB23"),
]

# Color Tokens collection, Mode 1: each semantic name aliases one of the
# four primitives above. Two pairs of aliases share a VariableID target in
# the source file (see module docstring) -- kept explicit here rather than
# collapsed, since a future redesign may want to split them.
SEMANTIC = [
    # token,                 primitive
    ("bg-page", "desert-cream"),
    ("bg-inverse", "kingfisher"),
    ("text-h1", "kingfisher"),
    ("text-h1-inverse", "shallow-lagoon"),
    ("text-body", "kingfisher"),
    ("text-body-inverse", "white"),
    ("accent", "salmon"),
    ("accent-hover", "shallow-lagoon"),
]

# token: (desktop, tablet, mobile), from the Fonts / Layout Spacing
# collections' Desktop/Tablet/Mobile modes.
RESPONSIVE = [
    ("type-3xl", 96, 64, 48),
    ("type-xl", 36, 28, 24),
    ("type-lg", 24, 20, 18),
    ("type-md", 20, 18, 16),
    # The cursive wordmark ("Angelo Outlaw" in Yesteryear) is sized outside
    # the shared type scale in the source file -- its own explicit stops.
    ("type-wordmark", 100, 60, 36),
    ("space-xs", 8, 6, 4),
    ("space-sm", 16, 8, 4),
    ("space-md", 32, 24, 16),
    ("space-lg", 64, 32, 16),
    ("space-xl", 80, 64, 32),
]

# Fixed at every breakpoint (Max-width / Max Width variables both read 1280).
CONTAINER_MAX = 1280


def ramp(lo_val, hi_val, lo_vw, hi_vw):
    """Fluid value between two viewport anchors, in rem + vw. Falls back to
    a flat px value when the two ends agree (the spacing scale plateaus
    between tablet and desktop for some tokens)."""
    if lo_val == hi_val:
        return f"{lo_val}px"
    slope = (hi_val - lo_val) / (hi_vw - lo_vw)
    intercept = lo_val - slope * lo_vw
    lo, hi = min(lo_val, hi_val), max(lo_val, hi_val)
    return (
        f"clamp({lo}px, {intercept / ROOT_FONT:.4f}rem + "
        f"{slope * 100:.4f}vw, {hi}px)"
    )


def main():
    lines = [
        "/*",
        " * designoutlaw.com — design tokens",
        " *",
        " * GENERATED by design/tokens/generate_tokens.py — do not edit by hand.",
        " *",
        " * Names map 1:1 to the Figma variables (see the module docstring for",
        " * how the semantic color aliases were resolved). Responsive tokens",
        " * interpolate fluidly between the mobile stop (375px) and the desktop",
        " * stop (1440px); the Figma tablet stop is a checkpoint on that ramp,",
        " * not a hard step.",
        " */",
        "",
        ":root {",
        "  /* ---- Color primitives ---- */",
    ]
    for name, hexv in PRIMITIVES:
        lines.append(f"  --{name}: {hexv};")

    lines += [
        "",
        "  /* ---- Semantic colors ---- */",
    ]
    for token, primitive in SEMANTIC:
        lines.append(f"  --{token}: var(--{primitive});")

    lines += [
        "",
        "  /* ---- Type families ---- */",
        '  --font-heading: "Gelasio", Georgia, "Times New Roman", serif;',
        '  --font-body: "Poppins", system-ui, -apple-system, sans-serif;',
        '  --font-wordmark: "Yesteryear", cursive;',
        "",
        "  /* ---- Line heights (relative, so they ride the fluid ramp) ---- */",
        "  --lh-heading: 1.15;",
        "  --lh-body: 1.3;",
        "  --lh-wordmark: 1;",
        "",
        "  /* ---- Layout ---- */",
        f"  --container-max: {CONTAINER_MAX}px;",
        "",
        "  /* ---- Responsive scale (segment 1: mobile -> tablet) ---- */",
    ]
    for name, desktop, tablet, mobile in RESPONSIVE:
        lines.append(f"  --{name}: {ramp(mobile, tablet, VW_MIN, VW_TABLET)};")

    lines += [
        "}",
        "",
        "/* Segment 2 of the ramp: tablet -> desktop. Two segments hit all",
        "   three Figma stops exactly; a single ramp across the full range",
        "   would undershoot tokens that plateau between tablet and desktop. */",
        "@media (min-width: 768px) {",
        "  :root {",
    ]
    for name, desktop, tablet, mobile in RESPONSIVE:
        lines.append(f"    --{name}: {ramp(tablet, desktop, VW_TABLET, VW_MAX)};")
    lines += ["  }", "}", ""]

    out = Path(__file__).resolve().parent / "tokens.css"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
